CREATE DATABASE PROVA_JACKSON;

CREATE TABLE HANGAR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOCAL VARCHAR(255),
    ID_AVIAO  INT
);

CREATE TABLE AVIAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(255),
    MODELO VARCHAR(255),
    PREFIXO VARCHAR(3),
    CAPACIDADE INT,
    ID_COMPANHIA INT
);

CREATE TABLE COMPANHIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    CNPJ VARCHAR(14)
);

CREATE TABLE HELICOPTERO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(255),
    MODELO VARCHAR(255),
    COR VARCHAR(255),
    CAPACIDADE INT
);

CREATE TABLE PISTA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(255)
);

CREATE TABLE VOO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(255),
    DATA VARCHAR(8),
    HORA VARCHAR(4),
    ORIGEM VARCHAR(3),
    DESTINO VARCHAR(3),
    PILOTO VARCHAR(255),
    COPILOTO VARCHAR(255),
    OBSERVACAO VARCHAR(255),
    ID_PISTA INT,
    ID_AVIAO INT,
    ID_HELICOPTERO INT,
    ID_JATO INT
);

CREATE TABLE JATO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(255),
    MODELO VARCHAR(255),
    COR VARCHAR(255),
    VELOCIDADE INT
);



ALTER TABLE HANGAR
ADD FOREIGN KEY (ID_AVIAO) REFERENCES AVIAO(ID);

ALTER TABLE AVIAO
ADD FOREIGN KEY (ID_COMPANHIA) REFERENCES COMPANHIA(ID);

ALTER TABLE VOO 
ADD FOREIGN KEY (ID_PISTA) REFERENCES PISTA(ID);

ALTER TABLE VOO 
ADD FOREIGN KEY (ID_AVIAO) REFERENCES AVIAO(ID);

ALTER TABLE VOO
ADD FOREIGN KEY (ID_HELICOPTERO) REFERENCES HELICOPTERO(ID);

ALTER TABLE VOO
ADD FOREIGN KEY (ID_JATO) REFERENCES JATO(ID);